---
title: "classifier_performance"
author: "undina"
date: "2024-07-12"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(cowplot)
knitr::opts_chunk$set(echo = TRUE)
```



## Get Performance

```{r}
gpt35_rag <- read_csv('../results/classifier_rag_gpt35_perform.csv')
gpt35_rag %>% head()

gpt35_rag %>% 
  ggplot(mapping =  aes(x = model, y = f1, fill = sections)) +
  geom_boxplot() + 
  geom_hline(yintercept = 0.9, linetype = 'dashed') + 
  theme_cowplot() +
  facet_wrap(~embed_model) + 
  ylim(0,1)
```


```{r}
perform_gpt35 <- read_csv('../results/classifier_gpt35_perform.csv') %>% mutate(sections = 'all') %>% 
                bind_rows(gpt35_rag %>% 
                            filter(sections == 'WP'))
perform_gpt35 %>% head()
```


```{r}
perform_rag <- read_csv('../results/classifier_rag_perform.csv') %>% mutate(gpt_model = 'gpt-4')
perform_rag
```


```{r}
performance <- read_csv('../results/classifier_perform.csv') %>% mutate('embed_model' = 'ember-v1',
                                                                        'gpt_model' = 'gpt-4')
perform_SFR <- read_csv('../results/classifier_SFR_perform.csv') %>% mutate('embed_model' = 'SFR-Embedding-Mistral',
                                                                            'gpt_model' = 'gpt-4')
performance <- performance %>% bind_rows(perform_SFR) %>% bind_rows(perform_rag) 
performance %>% head()
```

```{r,fig.width=8, fig.height=5}
performance %>% mutate(sections = 'all') %>%
  rbind(perform_gpt35) %>% filter(gpt_model == 'gpt-3.5', embed_model=='SFR-Embedding-Mistral') %>%
  select(mode, condition, model, embed_model, gpt_model, f1, hold_f1) %>%
  pivot_longer(f1:hold_f1, names_to = 'metric', values_to = 'val') %>%
  mutate(group = ifelse(grepl('hold', metric), 'Validation (Hold-Out)', 'Test'),
         model = case_when(model == 'logistic' ~ 'Logistic',
                           model == 'knn' ~ 'KNN',
                           model == 'rf' ~ 'Random Forest'),
         mode = case_when(mode == 'basic' ~ 'Baseline',
                          mode == 'inprompt' ~ 'In Prompt',
                          mode == 'rag' ~ 'RAG')) %>% filter(model == 'Logistic') %>%
ggplot(mapping = aes(x = condition, y = val, fill = mode, color = condition)) +
  geom_boxplot() +
  geom_hline(yintercept = 0.75, linetype = 'dashed') + 
  theme_cowplot() +
  facet_wrap(~group) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
       # legend.position = c(0.73,0.15)) + 
  ylim(0,1) + ylab('AUROC') + xlab('SPL Integration')
ggsave('../figures/classification_results.png', bg = 'white', dpi = 1200, width = 8, height = 5)
```



