---
title: "gpt_manual_annot_meddra_pt"
author: "undina"
date: "2024-07-01"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
gpt_annotation <- read_csv('data/gpt_annotation_meddra_pt_isa.csv') %>% mutate(meddra_term = str_to_lower(meddra_term))
gpt_annotation %>% head()
```

```{r}
gpt_votes <- gpt_annotation %>%
  group_by(meddra_term, meddra_pt_id) %>%
  summarise_all(sum) %>%
  pivot_longer(AKI:GIB, names_to = 'condition_name', values_to = 'votes') %>%
  filter(votes > 0) %>%
  arrange(condition_name, desc(votes)) %>%
  select(condition_name, meddra_pt_id, meddra_term, votes)
gpt_votes %>% head()
gpt_votes %>% write_csv('gpt_annot_votes_isa.csv')
```

```{r}
onsides_latest_release %>%
  inner_join(gpt_votes %>%
               mutate(condition_name = case_when(condition_name == 'AKI' ~ 'acute kidney injury',
                                                 condition_name == 'ALI' ~ 'acute liver injury',
                                                 condition_name == 'AMI' ~ 'acute myocardial infarction',
                                                 condition_name == 'GIB' ~ 'gi bleed')),
             by = c('pt_meddra_id' = 'meddra_pt_id',
                                    'pt_meddra_term' = 'meddra_term')) %>%
  select(ingredients_names, condition_name, pt_meddra_term, pt_meddra_id) %>%
  mutate(condition_name = str_to_lower(condition_name)) %>%
  inner_join(pryan_set, by = c('condition_name', 'ingredients_names'='drug_name')) %>%
  group_by(condition_name) %>%
  summarise(num_drugs = n_distinct(drug_concept_id)) %>%
  inner_join(pryan_set %>% group_by(condition_name) %>% summarise(ref_drugs = n_distinct(drug_concept_id))) %>%
  mutate(prop = num_drugs/ref_drugs)
```


## Check annotation -> drug

```{r}
onsides_latest_release = read_csv('./data/adverse_reactions_active_labels.csv.gz') %>%
              filter(num_ingredients == 1,!is.na(ingredients_names)) %>%
              mutate(pt_meddra_term = str_to_lower(pt_meddra_term), 
                     ingredients_names = str_to_lower(ingredients_names))
onsides_latest_release %>% head()
```

```{r}
onsides_latest_release %>%
  inner_join(gpt_votes %>% filter(votes >= 3), by = c('pt_meddra_id' = 'meddra_pt_id',
                                    'pt_meddra_term' = 'meddra_term')) %>%
  select(ingredients_names, condition_name, pt_meddra_term, pt_meddra_id, votes) %>%
  # group_by(condition_name) %>%
  summarise(unique_ingredients = n_distinct(ingredients_names))
```



## Check Condition - Drug count using HLT

```{r}
meddra_hlt <- read_csv('data/meddra_HLT_mapping.csv') %>% mutate(meddra_pt_term = str_to_lower(meddra_pt_term))
meddra_hlt %>% head()
```


```{r}
onsides_latest_release %>%
  inner_join(meddra_hlt, by = c('pt_meddra_id' = 'meddra_pt_id',
                                    'pt_meddra_term' = 'meddra_pt_term')) %>%
  select(ingredients_names, condition_name, pt_meddra_term, pt_meddra_id) %>%
  # group_by(condition_name) %>%
  summarise(n_distinct(ingredients_names))
```


```{r}
onsides_latest_release %>%
  inner_join(meddra_hlt, by = c('pt_meddra_id' = 'meddra_pt_id',
                                    'pt_meddra_term' = 'meddra_pt_term')) %>%
  select(ingredients_names, condition_name, pt_meddra_term, pt_meddra_id) %>%
  mutate(condition_name = str_to_lower(condition_name),
         condition_name = ifelse(condition_name == 'gi bleeding', 'gi bleed', condition_name)) %>% 
  inner_join(pryan_set, by = c('condition_name', 'ingredients_names'='drug_name')) %>%
  group_by(condition_name) %>%
  summarise(num_drugs = n_distinct(drug_concept_id)) %>%
  inner_join(pryan_set %>% group_by(condition_name) %>% summarise(ref_drugs = n_distinct(drug_concept_id))) %>%
  mutate(prop = num_drugs/ref_drugs)
```


## Meddra LLT -> Meddra PT

```{r}
meddra_llt <- read_csv('data/meddra_LLT_to_PT.csv') %>% mutate(meddra_pt_term = str_to_lower(meddra_pt_term))
meddra_llt %>% head()
```

```{r}
onsides_latest_release %>%
  inner_join(meddra_llt, by = c('pt_meddra_id' = 'meddra_pt_id',
                                    'pt_meddra_term' = 'meddra_pt_term')) %>%
  select(ingredients_names, condition_name, pt_meddra_term, pt_meddra_id) %>%
  # group_by(condition_name) %>% 
  summarise(n_distinct(ingredients_names))
```

```{r}
pryan_set <- read_csv('data/pryan_reference_set_ades.csv') %>% 
        filter(affect == 1) %>%
        mutate(drug_name = str_to_lower(drug_name),
               condition_name = str_to_lower(condition_name),
               drug_name = ifelse(drug_name == 'olmesartan medoxomil', 'olmesartan', drug_name))      
pryan_set %>% head()
pryan_set %>% group_by(condition_name) %>% summarise(ref_drugs = n_distinct(drug_concept_id))
```


```{r}
onsides_latest_release %>%
  inner_join(meddra_llt, by = c('pt_meddra_id' = 'meddra_pt_id',
                                    'pt_meddra_term' = 'meddra_pt_term')) %>%
  select(ingredients_names, condition_name, pt_meddra_term, pt_meddra_id) %>%
  mutate(condition_name = str_to_lower(condition_name)) %>%
  inner_join(pryan_set, by = c('condition_name', 'ingredients_names'='drug_name')) %>%
  group_by(condition_name) %>%
  summarise(num_drugs = n_distinct(drug_concept_id)) %>%
  inner_join(pryan_set %>% group_by(condition_name) %>% summarise(ref_drugs = n_distinct(drug_concept_id))) %>%
  mutate(prop = num_drugs/ref_drugs)
```



