---
title: "get_pos_nonpos_pairs"
author: "undina"
date: "2024-07-06"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = TRUE)
```


### Get Data


**Onsides extracted ADRs and MedDRA PT mappings**
```{r}
adr_section = # read_csv('../data/20240312/adverse_reactions_active_labels.csv.gz') %>%
  read_csv('../../20231113_onsides/adverse_reactions_active_labels.csv.gz') %>%
              filter(num_ingredients == 1) %>%
  mutate(section = 'adr')
warnings = # read_csv('../data/20240312/boxed_warnings_active_labels.csv.gz') %>%
  read_csv('../../20231113_onsides/boxed_warnings_active_labels.csv.gz') %>%
             filter(num_ingredients == 1) %>%
             mutate(pt_meddra_term = str_to_lower(pt_meddra_term),
                    section = 'warning')
adr_section <- adr_section %>% bind_rows(warnings)
# updated meddra mapping
meddra_reference_map <- read_csv('../data/meddra_LLT_to_PT.csv') %>%
      rename(pt_meddra_term = meddra_term) %>%
      mutate(condition_name = case_when(condition_name == 'AKI' ~ 'acute kidney injury',
                                        condition_name == 'ALI' ~ 'acute liver injury',
                                        condition_name == 'AMI' ~ 'acute myocardial infarction',
                                        condition_name == 'GIB' ~ 'gi bleed'),
             pt_meddra_term = str_to_lower(pt_meddra_term))
adr_condition_name = adr_section %>%
    mutate(pt_meddra_term = str_to_lower(pt_meddra_term)) %>%
    left_join(
      meddra_reference_map, by = c('pt_meddra_id' = 'meddra_pt_id')
      ) %>%
  filter(!is.na(ingredients_names)) %>%
  select(condition_name, pt_meddra_term, pt_meddra_id, ingredients_names, ingredients_rxcuis, set_id) %>%
  distinct() %>%
  mutate(ingredients_names = str_to_lower(ingredients_names))
adr_condition_name %>% head()
```

**Get Reference Set**
```{r}
pryan_set <- read_csv('../data/pryan_reference_set_ades.csv') %>% 
        mutate(drug_name = str_to_lower(drug_name),
               condition_name = str_to_lower(condition_name),
               drug_name = ifelse(drug_name == 'olmesartan medoxomil', 'olmesartan', drug_name))      
pryan_set %>% filter(affect == 1) %>% group_by(condition_name) %>% summarise(n_distinct(drug_concept_id))
```

**remove bad pairs**
```{r}
# removing bad negative controls
adr_condition_name %>%
      filter(!is.na(condition_name)) %>%
      mutate(onsides = 1) %>%
      full_join(pryan_set %>% mutate(reference = 1),
                by = c('condition_name', 'ingredients_names'='drug_name')) %>%
      replace_na(list('onsides' = 0,
                      'reference' = 0)) %>%
      select(condition_name, ingredients_names, onsides, reference, affect) %>%
      distinct() %>%
      filter(affect == 0,
             onsides == 1,
             reference == 1)
```

```{r}
# removing bad positive controls --- in reference set and not in onsides
adr_condition_name %>%
      filter(!is.na(condition_name)) %>%
      mutate(onsides = 1) %>%
      full_join(pryan_set %>% mutate(reference = 1),
                by = c('condition_name', 'ingredients_names'='drug_name')) %>%
      replace_na(list('onsides' = 0,
                      'reference' = 0)) %>%
      select(condition_name, ingredients_names, onsides, reference, affect) %>%
      distinct() %>%
      filter(affect == 1,
             onsides == 0,
             reference == 1) %>% dim
```


## Get the set of drug_names left

```{r}
onsides_drugs <- adr_condition_name %>% 
                  filter(!is.na(condition_name)) %>%
                  anti_join(exclude_positive_controls, by = c('ingredients_names')) %>%
                  anti_join(exclude_negative_controls, by = 'ingredients_names') %>%
                  distinct(ingredients_names)
```



```{r}
adr_condition_name %>%
      filter(!is.na(condition_name)) %>%
      mutate(onsides = 1) %>%
      full_join(pryan_set %>% mutate(reference = 1),
                by = c('condition_name', 'ingredients_names'='drug_name')) %>%
      replace_na(list('onsides' = 0,
                      'reference' = 0)) %>%
      select(condition_name, ingredients_names, onsides, reference, affect) %>%
      distinct() %>%
      filter(affect == 1,
             reference == 1) %>% 
      group_by(condition_name) %>%
      mutate(total_positive = sum(reference)) %>%
      group_by(condition_name, onsides, total_positive) %>% 
      summarise(num_drugs = n_distinct(ingredients_names)) %>%
      mutate(onsides = ifelse(onsides == 1, 'onsides', 'not_onsides')) %>%
      pivot_wider(names_from = onsides, values_from = num_drugs) %>%
      mutate(prop = round(onsides/(not_onsides + onsides) * 100, digits = 2))
```

## Union of drugs in Reference Set (positive controls) and in OnSIDES w/ADR

```{r}
adr_condition_name %>%
  filter(!is.na(condition_name)) %>% ## contain condition in reference set
  distinct(ingredients_names, condition_name) %>%
  full_join(pryan_set %>% filter(affect == 1) %>% select(ingredients_names = drug_name, condition_name)) %>%
  inner_join(adr_condition_name) %>% select(ingredients_names, condition_name, pt_meddra_term, pt_meddra_id) %>%
  distinct %>% head
```

```{r}
adr_condition_name %>%
      filter(!is.na(condition_name)) %>%
      mutate(onsides = 1) %>%
      full_join(pryan_set %>% mutate(reference = 1),
                by = c('condition_name', 'ingredients_names'='drug_name')) %>%
      replace_na(list('onsides' = 0,
                      'reference' = 0)) %>%
      select(condition_name, ingredients_names, onsides, reference, affect) %>%
      distinct() %>%
      filter(affect == 1,
             reference == 1) 
```


```{r}
adr_condition_name %>% filter(ingredients_names == "candesartan",
                              grepl(pattern = 'renal|kidney', pt_meddra_term)) %>%
  distinct(pt_meddra_term)
```
```{r}
warnings %>% filter(ingredients_names == "candesartan") 
```




```{r}
adr_section24 = read_csv('../data/20240312/adverse_reactions_active_labels.csv.gz') %>%
              filter(num_ingredients == 1) %>%
  mutate(section = 'adr', year24 = 1) %>% select(ingredients_names, pt_meddra_term, section, year24) %>% distinct
adr_section23 = read_csv('../../20231113_onsides/adverse_reactions_active_labels.csv.gz') %>%
              filter(num_ingredients == 1) %>%
  mutate(section = 'adr', year23 = 1) %>% select(ingredients_names, pt_meddra_term, section, year23) %>% distinct

adr_section23 %>%
  full_join(adr_section24) %>%
  filter(ingredients_names == 'candesartan') %>%
  replace_na(list('year23'=0, 'year24'=0)) %>% 
  filter(year23 * year24 == 0)
```




